### ISSUE TITLE
Investigate similar and earlier efforts

### ISSUE THREAD

**Issue by josteink** [josteink/emacs-oob-reboot#3]
There are other efforts at improving the default experience.

Starter kits or "distros":

* [prelude](https://github.com/bbatsov/prelude)
* [spacemacs](https://github.com/syl20bnr/spacemacs)

Smaller defaults packages or guides:

* [emacs-starter-kit](https://github.com/technomancy/emacs-starter-kit/)
* [better-defaults](https://github.com/technomancy/better-defaults)
* [sensible-defaults](https://github.com/hrs/sensible-defaults.el)

We should look into if there are good defaults we should adopt from these projects too.

Anyone other projects we should look into? Let us know! And id you find any good tweaks from these projects, feel free to discuss them below.

**Comment by dchrzanowski** [comment]
Fantastic suggestion!!! I'll try and compile a list of good defaults (in my opinion) as soon as I'll finish all the exams!

**Comment by bbenne10** [comment]
Would there be some value in also looking at something like [vim-sensible]( https://github.com/tpope/vim-sensible)? Obviously, the settings wouldn't directly translate into elisp, but - given that both Vim and Emacs suffer from the problem this repo is solving - it might give some general ideas of both issues and potential solutions? 

...provided no one balks too hard at reading vimscript, that is...

**Comment by bbenne10** [comment]
Seeing as I suggested it and I come from a vim-world, I figure I'm probably one of the better candidates for working through vim-sensible's changes. The general things that vim-sensible works with are:

* autoindent
* autocompletion support (in both code and menus)
* sets scrolloff reasonably (which is "start scrolling when your point is {n} lines from the top/bottom)
* sets sidescrolloff reasonably (which is "start scrolling when your point is {m} characters from the editor's side and the line is wider )
* reread the file automatically when external changes are detected
* intelligently sets a sane shell if the user's shell is `fish` (for posix compliance internally)

The rest of the changes feel overly specific to vim to be generally useful. 

And suggestions for Emacs changes: 
* autoindent: sort-of default? I've always found emacs indentation to be odd. I'm used to it now but the way it uses the tab key seemed odd at first.
* autocompletion support: company-mode and/or ido/ivy/helm?
* scrolloff: smooth-scrolling-mode has this for vertical scrolling, but I don't think has it for horizontal scrolling (I could open a PR, but I don't believe it's in ELPA?)
* reread the file automatically when external changes are detected: Not sure how to address this, but that's because I don't use the functionality
* intelligently sets a sane shell: this should be doable? I haven't looked to deeply

**Comment by justinjk007** [comment]
Hi @bbenne10 here is my 2 cents for indentation in emacs. When you are normally writing code, indentation works great, I mean I couldn't tell any difference when I was first starting out. Then when you copy and paste code or change something in the middle of something the indentation below gets messed up. So now what I would do is go and start TAB-ing every line like an idiot. Then I understood there are functions like indent-rigidly and so on. But then I came across this minor mode that make me forget about indenting all together. [aggressive-indent](http://elpa.gnu.org/packages/aggressive-indent.html). Even if I edit something on the top now may be like remove a function header and make two functions into one or so...everything will be indent rigidly automatically.

For autocompletion in menus, its is being discussed here already #20 
and autocompletion in code is already added I guess with [company](https://github.com/josteink/emacs-oob-reboot/blob/master/lisp/prog-mode-changes.el)

**Comment by josteink** [comment]
@bbenne10 wrote:

> reread the file automatically when external changes are detected

`(auto-revert-mode)` does this.

I have it enabled, but not automatically reloading a file when it changes (like accidentally gets overwritten) could be considered a safety feature, and settings auto-rever-mode on might be considered lowering the overall security. But I'll leave that argument for someone else. :)

**Comment by jackrusher** [comment]
Although we wouldn't want to default to `vi` keybindings, pretty much everything else about Spacemacs is very well done. Of these "starter kits", I think it's the most deserving of our attention in terms of making the editor more approachable.

**Comment by bbenne10** [comment]
With regard to indentation: Sure. It's far from an easily solved problem to deal with in all cases. I was simply commenting on how I found it odd (and frankly, much of that is born out of "I'm used to how vim does it".) All of that confusion is now behind me :P

with regard to auto-revert-mode: I'm just reporting what vim-sensible does. I personally think that auto-revert-mode is awesome and I'll use it personally, but there's maybe a discussion to be had about that? (If not - I'll happily put together a PR for it)

and spacemacs: Spacemacs also has an emacs key mode (or at the very least a "hybrid" mode which uses vim bindings outside of insert mode and enables a bunch of "emacs-isms" inside insertmode). I'm of the opinion that spacemacs goes too far, but I agree that it's worthy of attention.

**Comment by vindarel** [comment]
I have a list of similar projects on Wikemacs: http://wikemacs.org/wiki/Starter_Kits

in addition to yours:

- [Graphene](https://github.com/rdallasgray/graphene) "for refugees from GUI editors" 
- [Scimax](http://kitchingroup.cheme.cmu.edu/scimax), aimed at scientists, heavily tweaking org, babel "Scimax builds on Emacs, org-mode and programming tools to provide a rich authoring environment for writing, programming, research and teaching. "
- [emacs-kicker](http://tapoueh.org/blog/2011/04/emacs-kicker/), by Dimitri Fontaine (el-get,…), maintaining it for other colleagues (-> **good occasion to ask about user stories ?**), only 128 lines.
- [emacs-for-social science](https://github.com/jabranham/emacs-for-social-science)

**Comment by josteink** [comment]
I think recent changes to Emacs (eglot, tree-sitter, etc) has helped make Emacs much more usable OOB. Considering repo-purpose obsolete.

Closing all issues and archiving repo. Thanks to all contributors!
